{{- if .Values.initScripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dailytop.initScriptsName" . }}
  labels:
    {{- include "dailytop.labels" . | nindent 4 }}
data:
  {{- range $name, $script := .Values.initScripts }}
  {{ $name }}: |
    {{- $script | nindent 4 }}
  {{- end }}
{{- end }}
