{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dailytop.fullname" . }}-config
  labels:
    {{- include "dailytop.labels" . | nindent 4 }}
  {{- if .Values.persistence.config.retain }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  {{- with .Values.persistence.config.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
